#!/usr/bin/env python3
"""Writes tests/modding_zip_fixtures.h: synthetic zip/deflate/TPF bytes for
SudekiMP.ModdingCoreTest (no game data). Rerun after changing it:
    python3 tests/make_modding_zip_fixtures.py
"""
import io
import struct
import sys
import zipfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
sys.path.insert(0, str(ROOT / 'tests'))
import sudekimod  # noqa: E402
from sudekimod_test import zipcrypto_encrypt  # noqa: E402


def deflate(data, level=9):
    c = zlib.compressobj(level, zlib.DEFLATED, -15)
    return c.compress(data) + c.flush()


def make_tpf_deflated(files, comment):
    """Deflated + ZipCrypto members, XOR layer: what TexMod itself writes."""
    body, central = bytearray(), bytearray()
    for name, data in files.items():
        crc = zlib.crc32(data)
        blob = zipcrypto_encrypt(deflate(data), sudekimod.TPF_PASSWORD, crc >> 24)
        offset = len(body)
        n = name.encode('cp1252')
        body += struct.pack('<IHHHHHIIIHH', 0x04034b50, 20, 1, 8, 0, 0, crc, len(blob), len(data), len(n), 0)
        body += n + blob
        central += struct.pack('<IHHHHHHIIIHHHHHII', 0x02014b50, 20, 20, 1, 8, 0, 0, crc, len(blob), len(data),
                               len(n), 0, 0, 0, 0, 0, offset) + n
    end = struct.pack('<IHHHHIIH', 0x06054b50, 0, 0, len(files), len(files), len(central), len(body), len(comment))
    return sudekimod.tpf_unxor(bytes(body + central + end + comment))


text = b''.join(b'line %04d: the quick brown fox jumps over the lazy dog\n' % i for i in range(400))
fixed = deflate(b'hello hello hello sudeki', 9)          # small: fixed Huffman
dynamic = deflate(text, 9)                                # large: dynamic Huffman
stored = deflate(bytes(range(256)) * 3, 0)                # level 0: stored blocks

archive = io.BytesIO()
with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as z:
    z.writestr('MyMod/mod.ini', b'Format=SudekiMP.Mod/1\r\nName=Zip Mod\r\n')
    z.writestr('MyMod/textures/a.png', b'\x89PNG\r\n\x1a\nfake')
    z.writestr('MyMod/', b'')
zipped = archive.getvalue()

tpf = make_tpf_deflated({
    'texmod.def': b'0xAC57BC5D|SUDEKI.EXE_0xAC57BC5D.dds\r\n0x00000002|missing.png\r\n',
    'SUDEKI.EXE_0xAC57BC5D.dds': b'DDS ' + bytes(124) + bytes(range(64)),
}, b'JotaraKujo1988\r\nA \x93cooler\x94 blade')


def emit(name, data):
    lines = [f'static const unsigned char {name}[] = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',')
    lines.append('};')
    return '\n'.join(lines)


out = ['/* Generated by tests/make_modding_zip_fixtures.py: synthetic data only. */',
       f'#define FIXTURE_TEXT_SIZE {len(text)}u',
       f'#define FIXTURE_TEXT_CRC 0x{zlib.crc32(text):08x}u',
       emit('fixture_fixed', fixed), emit('fixture_dynamic', dynamic), emit('fixture_stored', stored),
       emit('fixture_zip', zipped), emit('fixture_tpf', tpf)]
(ROOT / 'tests' / 'modding_zip_fixtures.h').write_text('\n'.join(out) + '\n')
print('wrote tests/modding_zip_fixtures.h')
