#define SUDEKIMP_TALOS_MEMBERSHIP_ABI_TESTING 1
#include "hooks/talos_companion_membership_abi.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define ARRAY_COUNT(values) (sizeof(values) / sizeof((values)[0]))

#define CHECK(condition) do { \
    if (!(condition)) { \
        fprintf(stderr, "check failed at %s:%d: %s\n", \
            __FILE__, __LINE__, #condition); \
        exit(1); \
    } \
} while (0)

enum {
    PREFERRED_BASE = SUDEKIMP_TALOS_MEMBERSHIP_PREFERRED_BASE,
    IMAGE_SIZE = SUDEKIMP_TALOS_MEMBERSHIP_IMAGE_SIZE,
    RVA_GET_GROUP_PLAYERS = 0x00025100u,
    RVA_GET_PC = 0x00104480u,
    RVA_ADD_PLAYER = 0x00023230u,
    RVA_REMOVE_PLAYER = 0x00023390u,
    RVA_IS_PLAYER = 0x00023a00u,
    RVA_GET_INDEX = 0x00023ac0u,
    RVA_ALL_PENDING_LOADED = 0x00004fb0u,
    RVA_IN_COMBAT = 0x00004fa0u,
    RVA_ASYNC_ACTIVE = 0x000fdd80u,
    RVA_GEL_RESOLVER = 0x001bf4e0u,
    RVA_GEL_CLEANUP = 0x000015e0u,
    RVA_GEL_VTABLE = 0x002c0098u,
    RVA_GEL_DELETING_DESTRUCTOR = 0x00001b30u,
    RVA_GEL_CORE_DESTRUCTOR = 0x00001b50u,
    RVA_GEL_GET_RAW_ENTITY = 0x000017b0u,
    RVA_GEL_GET_TYPE_NAME = 0x00001820u,
    RVA_GEL_WRAPPER_FACTORY = 0x000019c0u,
    RVA_GET_PC_WRAPPER_CONSTRUCTOR = 0x00001c20u,
    RVA_PTR_REGISTRATION_CONSTRUCTOR = 0x000020d0u,
    RVA_PTR_REGISTRY_DELETE_ALL = 0x00002190u,
    RVA_PTR_REGISTRY_ERASE = 0x000021c0u,
    RVA_PTR_REGISTRY_FIND = 0x00002410u,
    RVA_GROUP_ADD_CORE = 0x00023280u,
    RVA_GROUP_REMOVE_CORE = 0x000233e0u,
    RVA_GROUP_REMOVE_EPILOGUE = 0x0009dba0u,
    RVA_UI_CONTROLLER_DISPATCH = 0x0009d9b0u,
    RVA_UI_CONTROLLER_VTABLE = 0x002caf9cu,
    RVA_UI_DISPATCH_JUMP_TABLE = 0x0009db70u,
    RVA_UI_DISPATCH_SELECTOR_TABLE = 0x0009db84u,
    RVA_HUD_CHILD_DISPATCH = 0x000a5930u,
    RVA_HUD_CHILD_VTABLE = 0x002cb3e4u,
    RVA_HUD_CHILD_JUMP_TABLE = 0x000a5aa8u,
    RVA_HUD_CHILD_SELECTOR_TABLE = 0x000a5ac4u,
    RVA_HUD_PORTRAIT_STATE_HANDLER = 0x000a5985u,
    RVA_PLAYER_SET_ARMED = 0x000db5f0u,
    RVA_STAT_DISPLAY_REFRESH = 0x00129780u,
    RVA_STAT_DISPLAY_CONSTRUCTOR = 0x00127ce0u,
    RVA_STAT_DISPLAY_PRIMARY_VTABLE = 0x002d21e4u,
    RVA_STAT_DISPLAY_SECONDARY_VTABLE = 0x002d2224u,
    RVA_STAT_BAR_FILL = 0x00182230u,
    RVA_STAT_BAR_FILL_EARLY_RETURN = 0x00182340u,
    RVA_STAT_BAR_FILL_RETURN = 0x00182344u,
    RVA_AI_LISTENER_VTABLE = 0x002ca244u,
    RVA_AI_LISTENER_ADD = 0x000f2b00u,
    RVA_AI_LISTENER_REMOVE = 0x000f2b30u,
    RVA_FORMATION_ADD = 0x000b2cb0u,
    RVA_FORMATION_REMOVE = 0x000b2d50u,
    RVA_FORMATION_CANONICALIZER = 0x000b3dd0u,
    RVA_GEL_RESOLVER_SEH = 0x002947f8u,
    RVA_GEL_FACTORY_SEH = 0x002947a3u,
    RVA_GEL_DESTRUCTOR_SEH = 0x00294783u,
    RVA_GEL_TYPE_NAME_TEXT = 0x002c0018u,
    RVA_PTR_OBJECT_VTABLE = 0x002c018cu,
    RVA_PTR_ALLOCATION_FAILURE_VTABLE = 0x002c017cu,
    RVA_PTR_REGISTRY_ERROR_TEXT = 0x002c0138u,
    RVA_PTR_REGISTRY_ROOT = 0x003c3904u,
    RVA_PTR_REGISTRY_COUNT = 0x003c3908u,
    RVA_UI_CONTROLLER_GLOBAL = 0x003c2f88u,
    RVA_UI_SCENE_GLOBAL = 0x00408d1cu,
    RVA_ASYNC_PENDING_GLOBAL = 0x003c30d8u,
    RVA_ASYNC_STREAM_GLOBAL = 0x003c30d4u,
    RVA_FORMATION_DEFAULT_DISTANCE = 0x002c3f54u,
    RVA_ACTIVE_GROUP_GLOBAL = 0x00408d94u,
    RVA_UI_DISPATCH_ID5_HANDLER = 0x0009da51u,
    RVA_UI_DISPATCH_ID7_HANDLER = 0x0009db14u,
    RVA_UI_DISPATCH_ID10_HANDLER = 0x0009d9deu,
    RVA_HUD_PORTRAIT_STATE_SETTER = 0x000aa910u,
    RVA_STAT_DISPLAY_PRIMARY_DESTRUCTOR = 0x0012a6c0u,
    RVA_STAT_DISPLAY_SECONDARY_DESTRUCTOR = 0x0012a800u,
    RVA_STAT_DISPLAY_CAMERA_SYNC = 0x0012a460u,
    RVA_STAT_DISPLAY_CAMERA_INIT = 0x00409e08u,
    RVA_STAT_DISPLAY_SAVED_BOUNDS = 0x003c303cu,
    RVA_STAT_DISPLAY_ACTIVE_BOUNDS = 0x0040cdc0u,
    RVA_CAMERA_MANAGER_GLOBAL = 0x003c2f30u,
    RVA_SQUARE_ROOT = 0x0028fd60u,
    RVA_HUD_RESOURCE_SELECTOR = 0x0012bb60u,
    RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE = 0x0012be50u,
    RVA_HUD_RESOURCE_INITIALIZED = 0x00409e09u,
    RVA_HUD_RESOURCE_TABLE_GLOBAL = 0x003c305cu,
    RVA_HUD_RESOURCE_INLINE_TEXT = 0x002d2258u,
    RVA_HUD_RESOURCE_ERROR_TEXT = 0x002d2290u,
    RVA_HUD_RESOURCE_DEFAULT_TEXT = 0x002d34d0u,
    RVA_HUD_RESOURCE_FALLBACK_TEXT = 0x00361650u,
    RVA_HUD_RESOURCE_MISSING_REPORT = 0x00012f70u,
    RVA_HUD_STRING_ASSIGN = 0x001b9fc0u,
    RVA_HUD_STRING_FREE = 0x00248916u,
    RVA_HUD_STRING_ALLOCATE = 0x0024884eu,
    RVA_HUD_STRING_COPY = 0x0024e600u,
    RVA_FLOAT_TO_INT = 0x0028f010u,
    RVA_SET_ARMED_RELEASE_ATTACHMENT = 0x000c77b0u,
    RVA_SET_ARMED_RESET_STATE = 0x000dad60u,
    RVA_SET_ARMED_BLEND = 0x000c3830u,
    RVA_STAT_FILL_SCALE_A = 0x002e3620u,
    RVA_STAT_FILL_SCALE_B = 0x002e3690u,
    RVA_STAT_FILL_SCALE_C = 0x002e37c0u
};

typedef struct RelocationFixture {
    uint32_t operand_rva;
    uint32_t target_rva;
    SudekiMpTalosMembershipSymbol symbol;
} RelocationFixture;

typedef struct CallFixture {
    uint32_t call_rva;
    uint32_t target_rva;
    SudekiMpTalosMembershipSymbol symbol;
} CallFixture;

typedef struct ByteFixture {
    uint32_t rva;
    SudekiMpTalosMembershipSymbol symbol;
} ByteFixture;

typedef struct StableRangeFixture {
    uint32_t rva;
    uint32_t byte_count;
    SudekiMpTalosMembershipSymbol symbol;
} StableRangeFixture;

static const RelocationFixture relocation_fixtures[] = {
    {RVA_GET_GROUP_PLAYERS + 1u, RVA_ACTIVE_GROUP_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_GROUP_PLAYERS},
    {RVA_ASYNC_ACTIVE + 2u, RVA_ASYNC_PENDING_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ASYNC_ACTIVE},
    {RVA_ASYNC_ACTIVE + 0x0bu, RVA_ASYNC_STREAM_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ASYNC_ACTIVE},
    {RVA_GEL_RESOLVER + 3u, RVA_GEL_RESOLVER_SEH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_RESOLVER},
    {RVA_GEL_VTABLE, RVA_GEL_DELETING_DESTRUCTOR,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_VTABLE + 0x10u, RVA_GEL_GET_RAW_ENTITY,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_VTABLE + 0x2cu, RVA_GEL_GET_TYPE_NAME,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_GET_TYPE_NAME + 1u, RVA_GEL_TYPE_NAME_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR + 3u, RVA_GEL_RESOLVER_SEH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 3u, RVA_GEL_FACTORY_SEH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x47u, RVA_GEL_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x0au, RVA_PTR_OBJECT_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x25u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x2du, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x36u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x68u,
        RVA_PTR_ALLOCATION_FAILURE_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 3u, RVA_GEL_DESTRUCTOR_SEH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x73u, RVA_PTR_OBJECT_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x85u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 2u, RVA_PTR_REGISTRY_COUNT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 0x11u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 0x28u, RVA_PTR_REGISTRY_COUNT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_FIND + 9u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x0bu, RVA_PTR_REGISTRY_ERROR_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x56u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x71u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x9eu, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0xbfu, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0xf5u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x132u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x1e0u, RVA_PTR_REGISTRY_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x22fu, RVA_PTR_REGISTRY_COUNT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x238u, RVA_PTR_REGISTRY_COUNT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GROUP_REMOVE_CORE + 0x1e6u, RVA_UI_CONTROLLER_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_AI_LISTENER_VTABLE + 0x18u, RVA_AI_LISTENER_ADD,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_AI_LISTENER_VTABLE + 0x1cu, RVA_AI_LISTENER_REMOVE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_FORMATION_CANONICALIZER + 8u,
        RVA_FORMATION_DEFAULT_DISTANCE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_CANONICALIZER},
    {RVA_GROUP_REMOVE_EPILOGUE + 1u, RVA_ACTIVE_GROUP_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_UI_CONTROLLER_VTABLE + 0x20u, RVA_UI_CONTROLLER_DISPATCH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x04u, RVA_UI_SCENE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x21u,
        RVA_UI_DISPATCH_SELECTOR_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x2au, RVA_UI_DISPATCH_JUMP_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x33u, RVA_ACTIVE_GROUP_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0xb2u, RVA_ACTIVE_GROUP_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x166u, RVA_ACTIVE_GROUP_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_DISPATCH_JUMP_TABLE, RVA_UI_DISPATCH_ID5_HANDLER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_DISPATCH_JUMP_TABLE + 4u, RVA_UI_DISPATCH_ID7_HANDLER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_DISPATCH_JUMP_TABLE + 8u, RVA_UI_DISPATCH_ID10_HANDLER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_HUD_CHILD_VTABLE + 0x2cu, RVA_HUD_CHILD_DISPATCH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_DISPATCH + 0x14u, RVA_HUD_CHILD_SELECTOR_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_DISPATCH + 0x1bu, RVA_HUD_CHILD_JUMP_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_JUMP_TABLE + 0x10u,
        RVA_HUD_PORTRAIT_STATE_HANDLER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_STAT_DISPLAY_CONSTRUCTOR + 0x2bu,
        RVA_STAT_DISPLAY_PRIMARY_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_CONSTRUCTOR + 0x32u,
        RVA_STAT_DISPLAY_SECONDARY_VTABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_PRIMARY_VTABLE,
        RVA_STAT_DISPLAY_PRIMARY_DESTRUCTOR,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_SECONDARY_VTABLE,
        RVA_STAT_DISPLAY_SECONDARY_DESTRUCTOR,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_BAR_FILL + 0x22u, RVA_STAT_FILL_SCALE_A,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL + 0x30u, RVA_STAT_FILL_SCALE_B,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL + 0x51u, RVA_STAT_FILL_SCALE_C,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x00bu, RVA_STAT_DISPLAY_CAMERA_INIT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x014u, RVA_UI_SCENE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x031u, RVA_STAT_DISPLAY_CAMERA_INIT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x038u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x044u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x050u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x05cu, RVA_STAT_DISPLAY_ACTIVE_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x062u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x068u, RVA_STAT_DISPLAY_SAVED_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x06eu, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x074u, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x07au, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x080u, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x086u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x08cu, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x092u, RVA_STAT_DISPLAY_SAVED_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0abu, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0b5u, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0c8u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0d2u, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0e5u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x0efu, RVA_STAT_DISPLAY_SAVED_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x102u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x126u, RVA_CAMERA_MANAGER_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x1a0u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x04u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x1afu, RVA_STAT_DISPLAY_ACTIVE_BOUNDS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x1b7u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x1c6u, RVA_STAT_DISPLAY_ACTIVE_BOUNDS + 0x08u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_HUD_RESOURCE_SELECTOR + 0x034u, RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x03au, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x042u, RVA_HUD_RESOURCE_INLINE_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x048u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x074u, RVA_HUD_RESOURCE_ERROR_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x079u, RVA_HUD_RESOURCE_FALLBACK_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x086u, RVA_HUD_RESOURCE_FALLBACK_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x08du, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x095u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x0c0u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x0ccu, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x0fau, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x106u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x138u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x144u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x176u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x182u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x1b4u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x1c0u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x1f2u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x1feu, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x230u, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x23cu, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x26eu, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x27au, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x2acu, RVA_HUD_RESOURCE_INITIALIZED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x2b8u, RVA_HUD_RESOURCE_TABLE_GLOBAL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR + 0x2e9u, RVA_HUD_RESOURCE_DEFAULT_TEXT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x00u,
        RVA_HUD_RESOURCE_SELECTOR + 0x038u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x04u,
        RVA_HUD_RESOURCE_SELECTOR + 0x08bu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x08u,
        RVA_HUD_RESOURCE_SELECTOR + 0x0beu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x0cu,
        RVA_HUD_RESOURCE_SELECTOR + 0x0f8u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x10u,
        RVA_HUD_RESOURCE_SELECTOR + 0x136u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x14u,
        RVA_HUD_RESOURCE_SELECTOR + 0x174u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x18u,
        RVA_HUD_RESOURCE_SELECTOR + 0x1b2u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x1cu,
        RVA_HUD_RESOURCE_SELECTOR + 0x1f0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x20u,
        RVA_HUD_RESOURCE_SELECTOR + 0x22eu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x24u,
        RVA_HUD_RESOURCE_SELECTOR + 0x26cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE + 0x28u,
        RVA_HUD_RESOURCE_SELECTOR + 0x2aau,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR}
};

static const CallFixture call_fixtures[] = {
    {RVA_GET_PC + 0x0bu, 0x00103fb0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_PC},
    {RVA_GET_PC + 0x16u, 0x00001c20u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_PC},
    {RVA_ADD_PLAYER + 0x0au, 0x00012e90u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_ADD_PLAYER + 0x19u, RVA_GEL_RESOLVER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_ADD_PLAYER + 0x30u, 0x00023280u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_ADD_PLAYER + 0x39u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x4au, 0x00001750u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x64u, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x74u, 0x000237b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x7du, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0xb5u, 0x00002000u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0xdcu, 0x000db5f0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0xfdu, 0x00129780u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_REMOVE_PLAYER + 0x0au, 0x00012e90u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_REMOVE_PLAYER + 0x19u, RVA_GEL_RESOLVER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_REMOVE_PLAYER + 0x31u, 0x000233e0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_REMOVE_PLAYER + 0x3au, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x53u, 0x00023f60u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1d2u, 0x00002000u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1eau, 0x0009dba0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_IS_PLAYER + 0x0au, 0x00012e90u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_IS_PLAYER + 0x19u, RVA_GEL_RESOLVER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_IS_PLAYER + 0x4eu, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_IS_PLAYER + 0x63u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_IS_PLAYER + 0x76u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_GET_INDEX + 0x0au, 0x00012e90u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_GET_INDEX + 0x19u, RVA_GEL_RESOLVER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_GET_INDEX + 0x56u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_GET_INDEX + 0x6bu, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_GET_INDEX + 0x7eu, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_GEL_DELETING_DESTRUCTOR + 4u, 0x00001b50u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_DELETING_DESTRUCTOR + 0x11u, 0x0024844fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR + 0x7bu, RVA_GEL_WRAPPER_FACTORY,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x20u, 0x002484fau,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x37u,
        RVA_PTR_REGISTRATION_CONSTRUCTOR,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x58u, 0x00001e00u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x15u, 0x002484fau,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x50u, 0x00002750u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x6cu, 0x00002070u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x7bu, RVA_PTR_REGISTRY_FIND,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x91u, RVA_PTR_REGISTRY_ERASE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x0fu, 0x00258df0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x1eu, 0x00002660u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0xb8u, 0x00002590u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x161u, 0x000024f0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x18fu, 0x00002540u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x1a8u, 0x000024f0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x1beu, 0x00002540u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x205u, 0x000024f0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x21cu, 0x00002540u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x225u, 0x0024844fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_GET_RAW_ENTITY + 0x20u, 0x00001750u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_AI_LISTENER_ADD + 0x14u, RVA_FORMATION_ADD,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_AI_LISTENER_ADD + 0x1du, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_AI_LISTENER_REMOVE + 0x14u, RVA_FORMATION_REMOVE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_AI_LISTENER_REMOVE + 0x1du, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_FORMATION_ADD + 0x38u, 0x00001750u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD},
    {RVA_FORMATION_ADD + 0x7eu, RVA_FORMATION_CANONICALIZER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD},
    {RVA_FORMATION_REMOVE + 0x5cu, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_FORMATION_REMOVE + 0x115u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_FORMATION_REMOVE + 0x1ccu, RVA_FORMATION_CANONICALIZER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_GROUP_REMOVE_EPILOGUE + 0x23u, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_GROUP_REMOVE_EPILOGUE + 0x30u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_GROUP_REMOVE_EPILOGUE + 0x173u, RVA_STAT_DISPLAY_REFRESH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_UI_CONTROLLER_DISPATCH + 0x42u, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x4fu, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x6au, RVA_FLOAT_TO_INT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x72u, 0x0012bb60u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x93u, 0x001b9fc0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0xbdu, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0xcau, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x17bu, 0x000015b0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x184u, RVA_GEL_CLEANUP,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_CONTROLLER_DISPATCH + 0x1afu, 0x000a63e0u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_HUD_PORTRAIT_STATE_HANDLER + 0x23u,
        RVA_HUD_PORTRAIT_STATE_SETTER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_PLAYER_SET_ARMED + 0x3bu, RVA_SET_ARMED_RELEASE_ATTACHMENT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_PLAYER_SET_ARMED + 0x42u, RVA_SET_ARMED_RESET_STATE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_PLAYER_SET_ARMED + 0x62u, RVA_SET_ARMED_BLEND,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_PLAYER_SET_ARMED + 0x8au, RVA_SET_ARMED_BLEND,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_STAT_DISPLAY_REFRESH + 0x50u, RVA_STAT_BAR_FILL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_REFRESH + 0x62u, RVA_STAT_BAR_FILL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_REFRESH + 0x69u, RVA_STAT_DISPLAY_CAMERA_SYNC,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_BAR_FILL + 0x3cu, RVA_FLOAT_TO_INT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_DISPLAY_CAMERA_SYNC + 0x181u, RVA_SQUARE_ROOT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_HUD_RESOURCE_SELECTOR + 0x7du,
        RVA_HUD_RESOURCE_MISSING_REPORT,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_STRING_ASSIGN + 0x44u, RVA_HUD_STRING_FREE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN},
    {RVA_HUD_STRING_ASSIGN + 0x5fu, RVA_HUD_STRING_ALLOCATE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN},
    {RVA_HUD_STRING_ASSIGN + 0x6eu, RVA_HUD_STRING_COPY,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN},
    {RVA_HUD_STRING_ASSIGN + 0x96u, RVA_HUD_STRING_FREE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN},
    {RVA_HUD_STRING_ASSIGN + 0xb4u, RVA_HUD_STRING_COPY,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN},
    {RVA_HUD_STRING_ASSIGN + 0xd8u, RVA_HUD_STRING_FREE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN}
};

static const ByteFixture stable_byte_fixtures[] = {
    {0u, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IMAGE},
    {RVA_GET_GROUP_PLAYERS,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_GROUP_PLAYERS},
    {RVA_GET_PC, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_PC},
    {RVA_ADD_PLAYER, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_ADD_PLAYER + 0x42u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x33u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x44u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0xa8u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x106u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_REMOVE_PLAYER, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_REMOVE_PLAYER + 0x43u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x2fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0xb6u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1d9u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1f5u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_IS_PLAYER, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IS_PLAYER},
    {RVA_GET_INDEX, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_INDEX},
    {RVA_ALL_PENDING_LOADED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ALL_PENDING_LOADED},
    {RVA_IN_COMBAT, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IN_COMBAT},
    {RVA_ASYNC_ACTIVE, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ASYNC_ACTIVE},
    {RVA_GEL_RESOLVER, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_RESOLVER},
    {RVA_GEL_CLEANUP, SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_CLEANUP},
    {RVA_GEL_GET_RAW_ENTITY,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR + 0xc5u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x1bu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0xa5u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 7u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 0x64u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x51u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0xa4u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 0x23u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 0x2fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_FIND + 0x61u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x22du,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x24au,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_DELETING_DESTRUCTOR + 0x0du,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_AI_LISTENER_ADD,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_AI_LISTENER},
    {RVA_FORMATION_ADD,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD},
    {RVA_FORMATION_ADD + 0x29u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD},
    {RVA_FORMATION_ADD + 0x77u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD},
    {RVA_FORMATION_REMOVE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_FORMATION_REMOVE + 0x1b9u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_FORMATION_REMOVE + 0x1c3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_FORMATION_CANONICALIZER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_CANONICALIZER},
    {RVA_FORMATION_CANONICALIZER + 31u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_CANONICALIZER},
    {RVA_GROUP_REMOVE_EPILOGUE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_UI_CONTROLLER_DISPATCH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_DISPATCH_SELECTOR_TABLE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_HUD_CHILD_DISPATCH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_PORTRAIT_STATE_HANDLER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_SELECTOR_TABLE + 0x11u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_PLAYER_SET_ARMED,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_STAT_DISPLAY_REFRESH,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_CONSTRUCTOR + 0x29u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_BAR_FILL,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL + 0x0cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL + 0x14u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL_EARLY_RETURN,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL_RETURN,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_BAR_FILL + 0x116u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL}
};

static const StableRangeFixture stable_range_fixtures[] = {
    {RVA_GROUP_ADD_CORE + 0x31u, 5u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x44u, 6u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0xa6u, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x106u, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x2du, 5u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0xb6u, 6u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1d7u, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1f5u, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR + 0xc2u, 6u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY + 0x1au, 2u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR + 6u, 2u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR + 0x51u, 14u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL + 0x22u, 4u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_FIND + 0x61u, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x22du, 2u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x236u, 2u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x24au, 3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_DELETING_DESTRUCTOR + 9u, 7u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_FORMATION_REMOVE + 0x1b9u, 13u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE}
};

/* Every byte in these audited code windows is independently rejected. This
 * includes rel32 and relocated operand bytes; their failure category/rva is
 * intentionally checked by the dedicated matrices below. */
static const StableRangeFixture full_byte_corruption_ranges[] = {
    {RVA_GROUP_ADD_CORE, 0x4fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x82u, 0x42u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_ADD_CORE + 0x102u, 9u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER},
    {RVA_GROUP_REMOVE_CORE, 0x3au,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x74u, 0x52u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1a6u, 0x3bu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GROUP_REMOVE_CORE + 0x1e4u, 0x14u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER},
    {RVA_GET_PC_WRAPPER_CONSTRUCTOR, 0xc8u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_WRAPPER_FACTORY, 0xa8u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRATION_CONSTRUCTOR, 0x71u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_CORE_DESTRUCTOR, 0xa7u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_GEL_DELETING_DESTRUCTOR, 0x1fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_DELETE_ALL, 0x30u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_FIND, 0x64u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE, 0x0bu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x0fu, 0x14u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_PTR_REGISTRY_ERASE + 0x220u, 0x2du,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GEL_VTABLE},
    {RVA_FORMATION_REMOVE + 0x1b9u, 13u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE},
    {RVA_GROUP_REMOVE_EPILOGUE, 0x194u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE},
    {RVA_UI_CONTROLLER_DISPATCH, 0x1bdu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_UI_DISPATCH_SELECTOR_TABLE, 6u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH},
    {RVA_HUD_CHILD_DISPATCH, 0x1fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_PORTRAIT_STATE_HANDLER, 0x2fu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_DISPATCH + 0x169u, 0x0eu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_HUD_CHILD_SELECTOR_TABLE + 0x11u, 1u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH},
    {RVA_PLAYER_SET_ARMED, 0x96u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED},
    {RVA_STAT_DISPLAY_REFRESH, 0x75u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_DISPLAY_CONSTRUCTOR + 0x29u, 0x0du,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH},
    {RVA_STAT_BAR_FILL, 0x117u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL},
    {RVA_STAT_DISPLAY_CAMERA_SYNC, 0x25eu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC},
    {RVA_HUD_RESOURCE_SELECTOR, 0x2eeu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE, 0x2cu,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR},
    {RVA_HUD_STRING_ASSIGN, 0xf3u,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN}
};

static uint16_t read_u16(const uint8_t *bytes) {
    uint16_t value;

    memcpy(&value, bytes, sizeof(value));
    return value;
}

static uint32_t read_u32(const uint8_t *bytes) {
    uint32_t value;

    memcpy(&value, bytes, sizeof(value));
    return value;
}

static void write_u32(uint8_t *bytes, uint32_t value) {
    memcpy(bytes, &value, sizeof(value));
}

static uint8_t *read_file(const char *path, size_t *size_out) {
    FILE *file;
    long file_size;
    uint8_t *bytes;

    file = fopen(path, "rb");
    if (file == NULL) return NULL;
    if (fseek(file, 0L, SEEK_END) != 0) {
        fclose(file);
        return NULL;
    }
    file_size = ftell(file);
    if (file_size <= 0L || fseek(file, 0L, SEEK_SET) != 0) {
        fclose(file);
        return NULL;
    }
    bytes = (uint8_t *)malloc((size_t)file_size);
    if (bytes == NULL || fread(bytes, 1u, (size_t)file_size, file) !=
            (size_t)file_size) {
        free(bytes);
        fclose(file);
        return NULL;
    }
    fclose(file);
    *size_out = (size_t)file_size;
    return bytes;
}

static uint8_t *map_pe32_image(
    const uint8_t *file,
    size_t file_size,
    size_t *image_size_out
) {
    uint32_t pe_offset;
    uint16_t section_count;
    uint16_t optional_size;
    uint32_t image_size;
    uint32_t header_size;
    size_t section_table;
    uint8_t *image;
    uint16_t section;

    if (file == NULL || file_size < 0x40u ||
        read_u16(file) != 0x5a4du) return NULL;
    pe_offset = read_u32(file + 0x3cu);
    if (pe_offset > file_size - 24u ||
        read_u32(file + pe_offset) != 0x00004550u ||
        read_u16(file + pe_offset + 4u) != 0x014cu) return NULL;
    section_count = read_u16(file + pe_offset + 6u);
    optional_size = read_u16(file + pe_offset + 20u);
    if (optional_size < 64u ||
        pe_offset + 24u + optional_size > file_size ||
        read_u16(file + pe_offset + 24u) != 0x010bu) return NULL;
    image_size = read_u32(file + pe_offset + 24u + 56u);
    header_size = read_u32(file + pe_offset + 24u + 60u);
    section_table = (size_t)pe_offset + 24u + optional_size;
    if (image_size == 0u || header_size > image_size ||
        header_size > file_size || section_count == 0u ||
        section_table > file_size ||
        (size_t)section_count > (file_size - section_table) / 40u) return NULL;
    image = (uint8_t *)calloc(1u, image_size);
    if (image == NULL) return NULL;
    memcpy(image, file, header_size);
    for (section = 0u; section < section_count; ++section) {
        const uint8_t *entry = file + section_table + (size_t)section * 40u;
        uint32_t destination = read_u32(entry + 12u);
        uint32_t raw_size = read_u32(entry + 16u);
        uint32_t source = read_u32(entry + 20u);

        if (source > file_size || raw_size > file_size - source ||
            destination > image_size || raw_size > image_size - destination) {
            free(image);
            return NULL;
        }
        if (raw_size != 0u) {
            memcpy(image + destination, file + source, raw_size);
        }
    }
    *image_size_out = image_size;
    return image;
}

static void expect_valid(const uint8_t *image, uint32_t logical_base) {
    SudekiMpTalosMembershipValidationResult result =
        SudekiMpTalosCompanionMembershipAbiValidateMappedImage(
            image, IMAGE_SIZE, logical_base);

    if (!result.seams_valid) {
        fprintf(stderr,
            "validation failed: failure=%u symbol=%u rva=%08x "
            "expected=%08x observed=%08x checks=%u\n",
            (unsigned)result.failure, (unsigned)result.failed_symbol,
            (unsigned)result.failed_rva, (unsigned)result.expected_value,
            (unsigned)result.observed_value,
            (unsigned)result.checks_completed);
    }
    CHECK(result.seams_valid == 1u);
    CHECK(result.failure == SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_OK);
    CHECK(result.failed_symbol ==
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_INVALID);
    CHECK(result.validated_symbol_mask == result.required_symbol_mask);
    CHECK(result.native_calls_permitted == 0u);
    CHECK(result.pure_validation_only == 1u);
    CHECK(result.external_sha256_required == 1u);
}

static void expect_failure(
    const uint8_t *image,
    size_t image_size,
    uint32_t logical_base,
    SudekiMpTalosMembershipValidationFailure failure,
    SudekiMpTalosMembershipSymbol symbol,
    uint32_t rva
) {
    SudekiMpTalosMembershipValidationResult result =
        SudekiMpTalosCompanionMembershipAbiValidateMappedImage(
            image, image_size, logical_base);

    CHECK(result.seams_valid == 0u);
    CHECK(result.failure == (uint32_t)failure);
    CHECK(result.failed_symbol == (uint32_t)symbol);
    CHECK(result.failed_rva == rva);
    CHECK(result.native_calls_permitted == 0u);
    CHECK(result.pure_validation_only == 1u);
    CHECK(result.external_sha256_required == 1u);
}

static void test_descriptor_is_validation_only(void) {
    SudekiMpTalosMembershipAbiDescriptor descriptor =
        SudekiMpTalosCompanionMembershipAbiDescribe();
    SudekiMpTalosMembershipSymbolDescriptor symbol;
    uint32_t index;

    CHECK(descriptor.abi_version == SUDEKIMP_TALOS_MEMBERSHIP_ABI_VERSION);
    CHECK(descriptor.preferred_image_base == PREFERRED_BASE);
    CHECK(descriptor.mapped_image_size == IMAGE_SIZE);
    CHECK(descriptor.symbol_count ==
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_COUNT);
    CHECK(descriptor.required_symbol_mask ==
        ((UINT32_C(1) << descriptor.symbol_count) - 1u));
    CHECK(descriptor.native_capacity == 4u);
    CHECK(descriptor.get_pc_wrapper_size == 0x18u);
    CHECK(descriptor.get_pc_wrapper_helper_rva == 0x00001c20u);
    CHECK(descriptor.get_pc_wrapper_factory_rva == 0x000019c0u);
    CHECK(descriptor.get_pc_wrapper_core_destructor_rva == 0x00001b50u);
    CHECK(descriptor.get_pc_wrapper_scalar_destructor_rva == 0x00001b30u);
    CHECK(descriptor.embedded_tptr_size == 0x0cu);
    CHECK(descriptor.embedded_tptr_offset == 0x0cu);
    CHECK(descriptor.ptr_object_registration_constructor_rva ==
        0x000020d0u);
    CHECK(descriptor.ptr_registry_find_rva == 0x00002410u);
    CHECK(descriptor.ptr_registry_erase_rva == 0x000021c0u);
    CHECK(descriptor.ptr_registry_delete_all_rva == 0x00002190u);
    CHECK(descriptor.ptr_registry_root_rva == 0x003c3904u);
    CHECK(descriptor.ptr_registry_count_rva == 0x003c3908u);
    CHECK(descriptor.group_add_core_rva == 0x00023280u);
    CHECK(descriptor.group_remove_core_rva == 0x000233e0u);
    CHECK(descriptor.group_remove_epilogue_rva ==
        RVA_GROUP_REMOVE_EPILOGUE);
    CHECK(descriptor.ui_controller_global_rva == RVA_UI_CONTROLLER_GLOBAL);
    CHECK(descriptor.ui_controller_vtable_rva == RVA_UI_CONTROLLER_VTABLE);
    CHECK(descriptor.ui_controller_dispatch_slot_offset == 0x20u);
    CHECK(descriptor.ui_controller_dispatch_rva ==
        RVA_UI_CONTROLLER_DISPATCH);
    CHECK(descriptor.ui_controller_hud_child_offset == 0x6cu);
    CHECK(descriptor.hud_child_vtable_rva == RVA_HUD_CHILD_VTABLE);
    CHECK(descriptor.hud_child_dispatch_slot_offset == 0x2cu);
    CHECK(descriptor.hud_child_dispatch_rva == RVA_HUD_CHILD_DISPATCH);
    CHECK(descriptor.character_arbiter_offset == 0x90u);
    CHECK(descriptor.player_set_armed_rva == RVA_PLAYER_SET_ARMED);
    CHECK(descriptor.character_stat_display_offset == 0xb0u);
    CHECK(descriptor.stat_display_refresh_rva == RVA_STAT_DISPLAY_REFRESH);
    CHECK(descriptor.stat_display_constructor_rva ==
        RVA_STAT_DISPLAY_CONSTRUCTOR);
    CHECK(descriptor.stat_display_primary_vtable_rva ==
        RVA_STAT_DISPLAY_PRIMARY_VTABLE);
    CHECK(descriptor.stat_display_secondary_vtable_rva ==
        RVA_STAT_DISPLAY_SECONDARY_VTABLE);
    CHECK(descriptor.stat_display_health_bar_offset == 0xd0u);
    CHECK(descriptor.stat_display_last_hp_offset == 0x16cu);
    CHECK(descriptor.stat_bar_renderer_offset == 0x34u);
    CHECK(descriptor.stat_bar_handle_offset == 0x4cu);
    CHECK(descriptor.stat_bar_count_offset == 0x50u);
    CHECK(descriptor.stat_bar_cache_offset == 0x58u);
    CHECK(descriptor.stat_bar_fill_rva == RVA_STAT_BAR_FILL);
    CHECK(descriptor.stat_bar_fill_early_return_rva ==
        RVA_STAT_BAR_FILL_EARLY_RETURN);
    CHECK(descriptor.stat_bar_fill_return_rva == RVA_STAT_BAR_FILL_RETURN);
    CHECK(descriptor.stat_display_camera_sync_rva ==
        RVA_STAT_DISPLAY_CAMERA_SYNC);
    CHECK(descriptor.stat_display_camera_init_rva ==
        RVA_STAT_DISPLAY_CAMERA_INIT);
    CHECK(descriptor.stat_display_camera_ui_scene_global_rva ==
        RVA_UI_SCENE_GLOBAL);
    CHECK(descriptor.stat_display_camera_saved_bounds_rva ==
        RVA_STAT_DISPLAY_SAVED_BOUNDS);
    CHECK(descriptor.stat_display_camera_active_bounds_rva ==
        RVA_STAT_DISPLAY_ACTIVE_BOUNDS);
    CHECK(descriptor.stat_display_camera_manager_global_rva ==
        RVA_CAMERA_MANAGER_GLOBAL);
    CHECK(descriptor.stat_display_camera_ui_scene_last_float_offset ==
        0x158u);
    CHECK(descriptor.stat_display_scene_node_offset == 0x58u);
    CHECK(descriptor.stat_display_owner_offset == 0xccu);
    CHECK(descriptor.stat_display_owner_node_offset == 0x08u);
    CHECK(descriptor.scene_node_dirty_word_offset == 0x2cu);
    CHECK(descriptor.scene_node_matrix_offset == 0x90u);
    CHECK(descriptor.scene_node_matrix_float_count == 16u);
    CHECK(descriptor.camera_manager_active_offset == 0x20u);
    CHECK(descriptor.camera_active_payload_offset == 0x34u);
    CHECK(descriptor.camera_payload_position_offset == 0xc0u);
    CHECK(descriptor.hud_resource_selector_rva ==
        RVA_HUD_RESOURCE_SELECTOR);
    CHECK(descriptor.hud_resource_selector_jump_table_rva ==
        RVA_HUD_RESOURCE_SELECTOR_JUMP_TABLE);
    CHECK(descriptor.hud_resource_initialized_rva ==
        RVA_HUD_RESOURCE_INITIALIZED);
    CHECK(descriptor.hud_resource_table_global_rva ==
        RVA_HUD_RESOURCE_TABLE_GLOBAL);
    CHECK(descriptor.hud_resource_inline_text_rva ==
        RVA_HUD_RESOURCE_INLINE_TEXT);
    CHECK(descriptor.hud_resource_error_text_rva ==
        RVA_HUD_RESOURCE_ERROR_TEXT);
    CHECK(descriptor.hud_resource_default_text_rva ==
        RVA_HUD_RESOURCE_DEFAULT_TEXT);
    CHECK(descriptor.hud_resource_fallback_text_rva ==
        RVA_HUD_RESOURCE_FALLBACK_TEXT);
    CHECK(descriptor.hud_resource_missing_report_rva ==
        RVA_HUD_RESOURCE_MISSING_REPORT);
    CHECK(descriptor.hud_resource_actor_component_offset == 0x94u);
    CHECK(descriptor.hud_resource_set_offset == 0x3cu);
    CHECK(descriptor.hud_resource_count_offset == 0x09u);
    CHECK(descriptor.hud_resource_entries_offset == 0x04u);
    CHECK(descriptor.hud_resource_id_offset == 0x19u);
    CHECK(descriptor.hud_resource_table_count_offset == 0x08u);
    CHECK(descriptor.hud_resource_table_data_offset == 0x10u);
    CHECK(descriptor.hud_resource_table_first_slot_offset == 0x4d8u);
    CHECK(descriptor.hud_resource_table_slot_stride == 4u);
    CHECK(descriptor.hud_resource_table_slot_count == 11u);
    CHECK(descriptor.hud_resource_first_table_id == 0x136u);
    CHECK(descriptor.hud_resource_selected_id_min == 1u);
    CHECK(descriptor.hud_resource_selected_id_max == 11u);
    CHECK(descriptor.hud_string_assign_rva == RVA_HUD_STRING_ASSIGN);
    CHECK(descriptor.hud_string_free_rva == RVA_HUD_STRING_FREE);
    CHECK(descriptor.hud_string_allocate_rva == RVA_HUD_STRING_ALLOCATE);
    CHECK(descriptor.hud_string_copy_rva == RVA_HUD_STRING_COPY);
    CHECK(descriptor.hud_portrait_gizmo_label_offset == 0x2e0u);
    CHECK(descriptor.hud_string_control_offset == 0u);
    CHECK(descriptor.hud_string_data_offset == 0x04u);
    CHECK(descriptor.hud_string_inline_mask == UINT32_C(0x80000000));
    CHECK(descriptor.hud_string_inline_capacity_utf16 == 0x1cu);
    CHECK(descriptor.hud_string_proof_max_utf16_units == 27u);
    CHECK(descriptor.group_members_offset == 0x90u);
    CHECK(descriptor.group_count_offset == 0xccu);
    CHECK(descriptor.formation_members_offset == 0xf4u);
    CHECK(descriptor.formation_count_offset == 0x124u);
    CHECK(descriptor.ai_manager_group_listener_offset == 0x44u);
    CHECK(descriptor.group_listener_add_slot_offset == 0x18u);
    CHECK(descriptor.group_listener_remove_slot_offset == 0x1cu);
    CHECK(descriptor.group_listener_to_formation_offset == 0xb0u);
    CHECK(descriptor.ai_manager_formation_offset == 0xf4u);
    CHECK(descriptor.supported_sha256_words[0] == 0x8ceb1d3cu);
    CHECK(descriptor.supported_sha256_words[7] == 0xb0dfbb94u);
    CHECK(strcmp(SUDEKIMP_TALOS_MEMBERSHIP_SUPPORTED_SHA256,
        "8ceb1d3cf667ad906f13252cb5bdf762eb018ebbecb8bffeb92f3b27b0dfbb94")
        == 0);
    CHECK(descriptor.pure_validation_only == 1u);
    CHECK(descriptor.native_calls_permitted == 0u);
    CHECK(descriptor.hooks_permitted == 0u);
    CHECK(descriptor.enabled_by_default == 0u);
    CHECK(descriptor.external_sha256_required == 1u);

    for (index = 0u; index < descriptor.symbol_count; ++index) {
        symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(index);
        CHECK(symbol.symbol == index);
        CHECK(symbol.validation_only == 1u);
    }
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        descriptor.symbol_count);
    CHECK(symbol.symbol == SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_INVALID);

    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_ADD_PLAYER);
    CHECK(symbol.rva == RVA_ADD_PLAYER);
    CHECK(symbol.validated_span == 0x45u);
    CHECK(symbol.calling_convention ==
        SUDEKIMP_TALOS_MEMBERSHIP_CALL_THISCALL);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ECX);
    CHECK(symbol.return_kind == SUDEKIMP_TALOS_MEMBERSHIP_RETURN_VOID);
    CHECK(symbol.stack_argument_bytes == 4u);
    CHECK(symbol.callee_pop_bytes == 4u);

    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_PLAYER);
    CHECK(symbol.rva == RVA_REMOVE_PLAYER);
    CHECK(symbol.validated_span == 0x46u);
    CHECK(symbol.calling_convention ==
        SUDEKIMP_TALOS_MEMBERSHIP_CALL_THISCALL);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ECX);
    CHECK(symbol.return_kind == SUDEKIMP_TALOS_MEMBERSHIP_RETURN_VOID);
    CHECK(symbol.stack_argument_bytes == 4u);
    CHECK(symbol.callee_pop_bytes == 4u);

    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_ADD);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ESI);
    CHECK(symbol.callee_pop_bytes == 4u);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_REMOVE);
    CHECK(symbol.calling_convention ==
        SUDEKIMP_TALOS_MEMBERSHIP_CALL_INTERNAL_STACK);
    CHECK(symbol.object_register ==
        SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_NONE);
    CHECK(symbol.callee_pop_bytes == 8u);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_FORMATION_CANONICALIZER);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_EAX);

    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_REMOVE_EPILOGUE);
    CHECK(symbol.rva == RVA_GROUP_REMOVE_EPILOGUE);
    CHECK(symbol.validated_span == 0x194u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_EDI);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_UI_CONTROLLER_DISPATCH);
    CHECK(symbol.rva == RVA_UI_CONTROLLER_DISPATCH);
    CHECK(symbol.validated_span == 0x1bdu);
    CHECK(symbol.stack_argument_bytes == 16u);
    CHECK(symbol.callee_pop_bytes == 16u);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_CHILD_DISPATCH);
    CHECK(symbol.rva == RVA_HUD_CHILD_DISPATCH);
    CHECK(symbol.validated_span == 0x1a6u);
    CHECK(symbol.return_kind == SUDEKIMP_TALOS_MEMBERSHIP_RETURN_BOOL_AL);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_PLAYER_SET_ARMED);
    CHECK(symbol.rva == RVA_PLAYER_SET_ARMED);
    CHECK(symbol.validated_span == 0x96u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ECX);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_REFRESH);
    CHECK(symbol.rva == RVA_STAT_DISPLAY_REFRESH);
    CHECK(symbol.validated_span == 0x75u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ESI);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_BAR_FILL);
    CHECK(symbol.rva == RVA_STAT_BAR_FILL);
    CHECK(symbol.validated_span == 0x117u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_EDI);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_STAT_DISPLAY_CAMERA_SYNC);
    CHECK(symbol.rva == RVA_STAT_DISPLAY_CAMERA_SYNC);
    CHECK(symbol.validated_span == 0x25eu);
    CHECK(symbol.calling_convention ==
        SUDEKIMP_TALOS_MEMBERSHIP_CALL_THISCALL);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ECX);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_RESOURCE_SELECTOR);
    CHECK(symbol.rva == RVA_HUD_RESOURCE_SELECTOR);
    CHECK(symbol.validated_span == 0x2eeu);
    CHECK(symbol.stack_argument_bytes == 4u);
    CHECK(symbol.callee_pop_bytes == 0u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_ECX);
    symbol = SudekiMpTalosCompanionMembershipAbiDescribeSymbol(
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_HUD_STRING_ASSIGN);
    CHECK(symbol.rva == RVA_HUD_STRING_ASSIGN);
    CHECK(symbol.validated_span == 0xf3u);
    CHECK(symbol.stack_argument_bytes == 4u);
    CHECK(symbol.callee_pop_bytes == 4u);
    CHECK(symbol.object_register == SUDEKIMP_TALOS_MEMBERSHIP_REGISTER_EDI);
}

static void test_metadata_rejection(const uint8_t *image) {
    SudekiMpTalosMembershipValidationResult result;

    result = SudekiMpTalosCompanionMembershipAbiValidateMappedImage(
        NULL, IMAGE_SIZE, PREFERRED_BASE);
    CHECK(result.failure ==
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_NULL_IMAGE);
    expect_failure(image, IMAGE_SIZE - 1u, PREFERRED_BASE,
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_IMAGE_SIZE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IMAGE, 0u);
    expect_failure(image, IMAGE_SIZE, 0u,
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_LOADED_BASE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IMAGE, 0u);
    expect_failure(image, IMAGE_SIZE, PREFERRED_BASE + 1u,
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_LOADED_BASE,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IMAGE, 0u);
}

static void test_post_load_image_base_is_exact(uint8_t *image) {
    const uint32_t pe_rva = read_u32(image + 0x3cu);
    const uint32_t rebased = 0x10000000u;
    uint32_t saved = read_u32(image + pe_rva + 52u);

    CHECK(saved == PREFERRED_BASE);
    write_u32(image + pe_rva + 52u, rebased);
    expect_failure(image, IMAGE_SIZE, PREFERRED_BASE,
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_PE_HEADER,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_IMAGE, pe_rva + 52u);
    write_u32(image + pe_rva + 52u, saved);
    expect_valid(image, PREFERRED_BASE);
}

static void test_each_stable_seam_rejects_corruption(uint8_t *image) {
    size_t index;

    for (index = 0u; index < ARRAY_COUNT(stable_byte_fixtures); ++index) {
        const ByteFixture *fixture = &stable_byte_fixtures[index];
        uint8_t saved = image[fixture->rva];
        SudekiMpTalosMembershipValidationFailure expected_failure =
            SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_STABLE_BYTES;

        image[fixture->rva] ^= 0x01u;
        expect_failure(image, IMAGE_SIZE, PREFERRED_BASE, expected_failure,
            fixture->symbol, fixture->rva);
        image[fixture->rva] = saved;
        expect_valid(image, PREFERRED_BASE);
    }
}

static void test_every_byte_of_critical_windows_rejects_corruption(
    uint8_t *image
) {
    size_t range_index;

    for (range_index = 0u;
            range_index < ARRAY_COUNT(stable_range_fixtures);
            ++range_index) {
        const StableRangeFixture *fixture =
            &stable_range_fixtures[range_index];
        uint32_t byte_index;

        for (byte_index = 0u; byte_index < fixture->byte_count;
                ++byte_index) {
            uint32_t rva = fixture->rva + byte_index;
            uint8_t saved = image[rva];

            image[rva] ^= 0x01u;
            expect_failure(image, IMAGE_SIZE, PREFERRED_BASE,
                SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_STABLE_BYTES,
                fixture->symbol, rva);
            image[rva] = saved;
            expect_valid(image, PREFERRED_BASE);
        }
    }
}

static void test_every_audited_chain_byte_rejects_corruption(
    uint8_t *image,
    uint32_t logical_base
) {
    size_t range_index;

    for (range_index = 0u;
            range_index < ARRAY_COUNT(full_byte_corruption_ranges);
            ++range_index) {
        const StableRangeFixture *fixture =
            &full_byte_corruption_ranges[range_index];
        uint32_t byte_index;

        for (byte_index = 0u; byte_index < fixture->byte_count;
                ++byte_index) {
            uint32_t rva = fixture->rva + byte_index;
            uint8_t saved = image[rva];
            SudekiMpTalosMembershipValidationResult result;

            image[rva] ^= 0x01u;
            result = SudekiMpTalosCompanionMembershipAbiValidateMappedImage(
                image, IMAGE_SIZE, logical_base);
            CHECK(result.seams_valid == 0u);
            CHECK(result.failure != SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_OK);
            CHECK(result.failed_symbol == (uint32_t)fixture->symbol);
            image[rva] = saved;
        }
    }
    expect_valid(image, logical_base);
}

static void apply_known_relocations(uint8_t *image, uint32_t logical_base) {
    size_t index;

    write_u32(image + read_u32(image + 0x3cu) + 52u, logical_base);

    for (index = 0u; index < ARRAY_COUNT(relocation_fixtures); ++index) {
        const RelocationFixture *fixture = &relocation_fixtures[index];

        write_u32(image + fixture->operand_rva,
            logical_base + fixture->target_rva);
    }
}

static void test_relocations_are_exact_and_base_aware(uint8_t *image) {
    size_t index;
    const uint32_t rebased = 0x10000000u;

    for (index = 0u; index < ARRAY_COUNT(relocation_fixtures); ++index) {
        const RelocationFixture *fixture = &relocation_fixtures[index];
        uint32_t saved = read_u32(image + fixture->operand_rva);

        write_u32(image + fixture->operand_rva, saved ^ 1u);
        expect_failure(image, IMAGE_SIZE, PREFERRED_BASE,
            SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_RELOCATED_OPERAND,
            fixture->symbol, fixture->operand_rva);
        write_u32(image + fixture->operand_rva, saved);
        expect_valid(image, PREFERRED_BASE);
    }

    apply_known_relocations(image, rebased);
    expect_valid(image, rebased);
    for (index = 0u; index < ARRAY_COUNT(relocation_fixtures); ++index) {
        const RelocationFixture *fixture = &relocation_fixtures[index];
        uint32_t saved = read_u32(image + fixture->operand_rva);

        write_u32(image + fixture->operand_rva, saved ^ 1u);
        expect_failure(image, IMAGE_SIZE, rebased,
            SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_RELOCATED_OPERAND,
            fixture->symbol, fixture->operand_rva);
        write_u32(image + fixture->operand_rva, saved);
        expect_valid(image, rebased);
    }
    write_u32(image + read_u32(image + 0x3cu) + 52u, PREFERRED_BASE);
    expect_failure(image, IMAGE_SIZE, PREFERRED_BASE,
        SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_RELOCATED_OPERAND,
        SUDEKIMP_TALOS_MEMBERSHIP_SYMBOL_GET_GROUP_PLAYERS,
        RVA_GET_GROUP_PLAYERS + 1u);
    apply_known_relocations(image, PREFERRED_BASE);
    expect_valid(image, PREFERRED_BASE);
}

static void test_each_rel32_target_is_exact(
    uint8_t *image,
    uint32_t logical_base
) {
    size_t index;

    for (index = 0u; index < ARRAY_COUNT(call_fixtures); ++index) {
        const CallFixture *fixture = &call_fixtures[index];
        uint32_t saved = read_u32(image + fixture->call_rva + 1u);
        int64_t target = (int64_t)fixture->call_rva + INT64_C(5) +
            (int64_t)(int32_t)saved;

        CHECK(image[fixture->call_rva] == 0xe8u);
        CHECK(target == (int64_t)fixture->target_rva);
        write_u32(image + fixture->call_rva + 1u, saved + 1u);
        expect_failure(image, IMAGE_SIZE, logical_base,
            SUDEKIMP_TALOS_MEMBERSHIP_VALIDATION_REL32_TARGET,
            fixture->symbol, fixture->call_rva);
        write_u32(image + fixture->call_rva + 1u, saved);
        expect_valid(image, logical_base);
    }
}

static void test_rebased_audited_chain_and_calls(uint8_t *image) {
    const uint32_t rebased = 0x10000000u;

    apply_known_relocations(image, rebased);
    expect_valid(image, rebased);
    test_every_audited_chain_byte_rejects_corruption(image, rebased);
    test_each_rel32_target_is_exact(image, rebased);
    apply_known_relocations(image, PREFERRED_BASE);
    expect_valid(image, PREFERRED_BASE);
}

int main(int argc, char **argv) {
    uint8_t *file;
    uint8_t *image;
    size_t file_size;
    size_t image_size;

    test_descriptor_is_validation_only();
    if (argc > 2) {
        fprintf(stderr,
            "usage: SudekiMP.TalosCompanionMembershipAbiTest.exe [SUDEKI.exe]\n");
        return 2;
    }
    image = (uint8_t *)malloc(IMAGE_SIZE);
    CHECK(image != NULL);
    CHECK(SudekiMpTalosCompanionMembershipAbiPopulateFixtureForTesting(
        image, IMAGE_SIZE, PREFERRED_BASE));
    expect_valid(image, PREFERRED_BASE);
    test_metadata_rejection(image);
    test_post_load_image_base_is_exact(image);
    test_each_stable_seam_rejects_corruption(image);
    test_every_byte_of_critical_windows_rejects_corruption(image);
    test_every_audited_chain_byte_rejects_corruption(
        image, PREFERRED_BASE);
    test_relocations_are_exact_and_base_aware(image);
    test_each_rel32_target_is_exact(image, PREFERRED_BASE);
    test_rebased_audited_chain_and_calls(image);
    free(image);

    if (argc == 2) {
        file = read_file(argv[1], &file_size);
        if (file == NULL) {
            fprintf(stderr, "failed to read PE image: %s\n", argv[1]);
            return 1;
        }
        image = map_pe32_image(file, file_size, &image_size);
        free(file);
        if (image == NULL) {
            fputs("failed to map PE32 image\n", stderr);
            return 1;
        }
        CHECK(image_size == IMAGE_SIZE);
        expect_valid(image, PREFERRED_BASE);
        test_every_audited_chain_byte_rejects_corruption(
            image, PREFERRED_BASE);
        test_relocations_are_exact_and_base_aware(image);
        test_each_rel32_target_is_exact(image, PREFERRED_BASE);
        test_rebased_audited_chain_and_calls(image);
        free(image);
    }
    puts("talos_companion_membership_abi_test: PASS");
    return 0;
}
