set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(SUDEKIMP_MINGW_ROOT "/usr/lib/sdk/mingw-w64")
set(CMAKE_C_COMPILER "${SUDEKIMP_MINGW_ROOT}/bin/i686-w64-mingw32-gcc")
set(CMAKE_RC_COMPILER "${SUDEKIMP_MINGW_ROOT}/bin/i686-w64-mingw32-windres")

set(CMAKE_FIND_ROOT_PATH "${SUDEKIMP_MINGW_ROOT}/i686-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
