"""Build the title label atlas from the bundled OFL font; requires Pillow.

The typeface is an approximation, not an identification of Sudeki's wordmarks.
No game images are used. Run from any directory; output is deterministic for a
given Pillow/FreeType build. Runtime has no font installation dependency.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "assets/fonts/fondamento/Fondamento-Regular.ttf"
EXPECTED = "ee03a7ccb3b7cdf3cd095d0cc34f9e70c16b1779cbc7c466bf9077323a6ea764"
LABELS = ["Continue", "New Game", "Multiplayer", "Options", "Credits",
          "Quit Game", "Create Game", "Join Game", "Back"]


def main():
    if hashlib.sha256(FONT.read_bytes()).hexdigest() != EXPECTED:
        raise ValueError("Unexpected source font; review before regenerating")
    font = ImageFont.truetype(str(FONT), 156)
    image = Image.new("RGBA", (512, 1024))
    for row, text in enumerate(LABELS):
        layers = []
        bounds = font.getbbox(text)
        for stroke in (9, 2):
            mask = Image.new("L", (1536, 240))
            draw = ImageDraw.Draw(mask)
            draw.text((768 - (bounds[0] + bounds[2]) / 2,
                       120 - (bounds[1] + bounds[3]) / 2), text,
                      font=font, fill=255, stroke_width=stroke, stroke_fill=255)
            layers.append(mask.resize((512, 80), Image.Resampling.LANCZOS))
        edge, fill = (list(layer.getdata()) for layer in layers)
        tile = Image.new("RGBA", (512, 80))
        pixels = []
        for e, f in zip(edge, fill):
            # Straight alpha: white fill over a dark outline, with coverage.
            e = max(e, f)
            gray = min(255, (255 * f + e // 2) // e) if e else 0
            pixels.append((gray, gray, gray, e))
        tile.putdata(pixels)
        image.paste(tile, (0, row * 80))
    runs = []
    previous, count = None, 0
    for gray, _, _, alpha in image.getdata():
        value = alpha << 8 | gray
        if previous == value and count < 65535:
            count += 1
        else:
            if count:
                runs.append(count << 16 | previous)
            previous, count = value, 1
    runs.append(count << 16 | previous)
    lines = ["/* Generated by tools/generate_title_font.py. Do not edit.",
             " * Fondamento by Brian J. Bonislawsky / Astigmatic, SIL OFL 1.1.",
             " * License: assets/fonts/fondamento/OFL.txt; source font SHA256:",
             " * " + EXPECTED + ". */",
             "static const uint32_t title_font_runs[] = {"]
    lines += ["    " + ",".join(f"0x{v:08x}u" for v in runs[i:i+8]) + ","
              for i in range(0, len(runs), 8)]
    lines += ["};", ""]
    # Keep the attribution/license in the DLL as well as the source package.
    lines += ["static const char title_font_license[] __attribute__((used)) ="]
    lines += ["    " + json.dumps(line + "\n") for line in
              (FONT.parent / "OFL.txt").read_text().splitlines()]
    lines += [";", ""]
    (ROOT / "src/ui/title_font.inc").write_text("\n".join(lines))
    print(f"Title font: {len(runs)} runs, {len(runs)*4} embedded bytes")


if __name__ == "__main__":
    main()
