"""Generate a bounded ASCII glyph atlas from the bundled OFL title typeface."""
from pathlib import Path
import hashlib
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "assets/fonts/fondamento/Fondamento-Regular.ttf"
EXPECTED = "ee03a7ccb3b7cdf3cd095d0cc34f9e70c16b1779cbc7c466bf9077323a6ea764"


def main():
    if hashlib.sha256(FONT.read_bytes()).hexdigest() != EXPECTED:
        raise ValueError("Unexpected font")
    font = ImageFont.truetype(str(FONT), 126)
    atlas = Image.new("RGBA", (512, 1024))
    advances = []
    for index, code in enumerate(range(32, 127)):
        masks = []
        for stroke in (6, 1):
            mask = Image.new("L", (192, 192))
            ImageDraw.Draw(mask).text((9, 144), chr(code), font=font,
                                     anchor="ls", fill=255, stroke_width=stroke)
            masks.append(mask.resize((64, 64), Image.Resampling.LANCZOS))
        pixels = []
        for edge, fill in zip(masks[0].getdata(), masks[1].getdata()):
            edge = max(edge, fill)
            gray = min(255, (255 * fill + edge // 2) // edge) if edge else 0
            pixels.append((gray, gray, gray, edge))
        tile = Image.new("RGBA", (64, 64)); tile.putdata(pixels)
        atlas.paste(tile, ((index % 8) * 64, (index // 8) * 64))
        advances.append(font.getlength(chr(code)) / 3 + 1)
    runs = []; previous = None; count = 0
    for gray, _, _, alpha in atlas.getdata():
        value = alpha << 8 | gray
        if previous == value and count < 65535:
            count += 1
        else:
            if count: runs.append(count << 16 | previous)
            previous, count = value, 1
    runs.append(count << 16 | previous)
    lines = ["/* Generated by tools/generate_lobby_font.py; Fondamento SIL OFL 1.1.",
             " * Attribution/license embedded alongside title_font.inc. */",
             "static const float lobby_glyph_advance[95] = {"]
    lines += ["    " + ",".join(f"{v:.4f}f" for v in advances[i:i+8]) + ","
              for i in range(0, 95, 8)]
    lines += ["};", "static const uint32_t lobby_font_runs[] = {"]
    lines += ["    " + ",".join(f"0x{v:08x}u" for v in runs[i:i+8]) + ","
              for i in range(0, len(runs), 8)]
    lines += ["};", ""]
    (ROOT / "src/ui/lobby_font.inc").write_text("\n".join(lines))
    print(f"Lobby font: {len(runs)} runs / {len(runs)*4} bytes")


if __name__ == "__main__":
    main()
